//
// Created by FAKE on 2026/6/4.
//
#include "lcd_mcu_init.h"
#include "lcd_mcu.h"
/* ---------------- NT35310 init helpers ---------------- */

/*
 * lcd_mcu_init.c
 *
 * 这里专门存放 NT35310 的厂家初始化序列。
 *
 * 为什么拆出来：
 * - 这部分寄存器很多，属于 LCD 控制器厂家给定的上电配置；
 * - lcd_mcu.c 里保留 FMC、窗口、GRAM 写入、Fill 等真正需要学习的主逻辑。
 *
 * 注意：
 * 1. 该函数由 LCD_MCU_Init() 调用；
 * 2. main.c 不需要直接调用；
 * 3. 不要删掉函数末尾对 g_lcd_mcu.cmd_set_x/cmd_set_y/cmd_write_ram 的赋值。
 */
void LCD_MCU_NT35310_RegInit(void)
{
    LCD_MCU_WriteReg(0xED);
    LCD_MCU_WriteData(0x01);
    LCD_MCU_WriteData(0xFE);

    LCD_MCU_WriteReg(0xEE);
    LCD_MCU_WriteData(0xDE);
    LCD_MCU_WriteData(0x21);

    LCD_MCU_WriteReg(0xF1);
    LCD_MCU_WriteData(0x01);
    LCD_MCU_WriteReg(0xDF);
    LCD_MCU_WriteData(0x10);

    /* VCOMvoltage */
    LCD_MCU_WriteReg(0xC4);
    LCD_MCU_WriteData(0x8F);  /* 5f */

    LCD_MCU_WriteReg(0xC6);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xE2);
    LCD_MCU_WriteData(0xE2);
    LCD_MCU_WriteData(0xE2);
    LCD_MCU_WriteReg(0xBF);
    LCD_MCU_WriteData(0xAA);

    LCD_MCU_WriteReg(0xB0);
    LCD_MCU_WriteData(0x0D);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x0D);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x11);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x19);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x21);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x2D);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x3D);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x5D);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x5D);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xB1);
    LCD_MCU_WriteData(0x80);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x8B);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x96);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xB2);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x02);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x03);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xB3);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xB4);
    LCD_MCU_WriteData(0x8B);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x96);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xA1);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xB5);
    LCD_MCU_WriteData(0x02);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x03);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x04);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xB6);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xB7);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x3F);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x5E);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x64);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x8C);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xAC);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xDC);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x70);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x90);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xEB);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xDC);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xB8);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xBA);
    LCD_MCU_WriteData(0x24);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xC1);
    LCD_MCU_WriteData(0x20);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x54);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xFF);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xC2);
    LCD_MCU_WriteData(0x0A);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x04);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xC3);
    LCD_MCU_WriteData(0x3C);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x3A);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x39);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x37);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x3C);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x36);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x32);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x2F);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x2C);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x29);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x26);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x24);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x24);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x23);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x3C);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x36);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x32);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x2F);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x2C);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x29);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x26);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x24);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x24);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x23);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xC4);
    LCD_MCU_WriteData(0x62);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x05);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x84);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xF0);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x18);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xA4);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x18);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x50);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x0C);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x17);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x95);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xF3);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xE6);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xC5);
    LCD_MCU_WriteData(0x32);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x44);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x65);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x76);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x88);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xC6);
    LCD_MCU_WriteData(0x20);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x17);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x01);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xC7);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xC8);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xC9);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xE0);
    LCD_MCU_WriteData(0x16);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x1C);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x21);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x36);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x46);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x52);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x64);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x7A);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x8B);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x99);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xA8);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xB9);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xC4);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xCA);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xD2);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xD9);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xE0);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xF3);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xE1);
    LCD_MCU_WriteData(0x16);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x1C);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x22);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x36);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x45);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x52);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x64);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x7A);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x8B);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x99);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xA8);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xB9);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xC4);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xCA);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xD2);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xD8);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xE0);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xF3);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xE2);
    LCD_MCU_WriteData(0x05);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x0B);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x1B);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x34);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x44);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x4F);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x61);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x79);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x88);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x97);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xA6);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xB7);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xC2);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xC7);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xD1);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xD6);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xDD);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xF3);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteReg(0xE3);
    LCD_MCU_WriteData(0x05);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xA);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x1C);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x33);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x44);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x50);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x62);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x78);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x88);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x97);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xA6);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xB7);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xC2);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xC7);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xD1);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xD5);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xDD);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xF3);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xE4);
    LCD_MCU_WriteData(0x01);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x01);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x02);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x2A);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x3C);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x4B);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x5D);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x74);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x84);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x93);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xA2);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xB3);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xBE);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xC4);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xCD);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xD3);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xDD);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xF3);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteReg(0xE5);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x02);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x29);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x3C);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x4B);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x5D);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x74);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x84);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x93);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xA2);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xB3);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xBE);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xC4);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xCD);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xD3);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xDC);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xF3);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xE6);
    LCD_MCU_WriteData(0x11);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x34);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x56);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x76);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x77);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x66);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x88);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x99);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xBB);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x99);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x66);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x55);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x55);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x45);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x43);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x44);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xE7);
    LCD_MCU_WriteData(0x32);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x55);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x76);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x66);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x67);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x67);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x87);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x99);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xBB);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x99);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x77);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x44);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x56);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x23);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x33);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x45);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xE8);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x99);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x87);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x88);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x77);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x66);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x88);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xAA);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0xBB);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x99);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x66);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x55);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x55);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x44);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x44);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x55);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xE9);
    LCD_MCU_WriteData(0xAA);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0x00);
    LCD_MCU_WriteData(0xAA);

    LCD_MCU_WriteReg(0xCF);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xF0);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x50);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xF3);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0xF9);
    LCD_MCU_WriteData(0x06);
    LCD_MCU_WriteData(0x10);
    LCD_MCU_WriteData(0x29);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0x3A);
    LCD_MCU_WriteData(0x55);  /* 66 */

    LCD_MCU_WriteReg(0x11);
    HAL_Delay(100);
    LCD_MCU_WriteReg(0x29);
    LCD_MCU_WriteReg(0x35);
    LCD_MCU_WriteData(0x00);

    LCD_MCU_WriteReg(0x51);
    LCD_MCU_WriteData(0xFF);
    LCD_MCU_WriteReg(0x53);
    LCD_MCU_WriteData(0x2C);
    LCD_MCU_WriteReg(0x55);
    LCD_MCU_WriteData(0x82);
    LCD_MCU_WriteReg(0x2c);

    /*
     * 原版初始化最后已经写 0x2C 进入 GRAM。
     * 这里再设置最小驱动使用的窗口/GRAM命令。
     */
    // g_lcd_mcu.cmd_set_x = 0x2A;
    // g_lcd_mcu.cmd_set_y = 0x2B;
    // g_lcd_mcu.cmd_write_ram = 0x2C;
    // g_lcd_mcu.id = LCD_MCU_ID_NT35310;
    // g_lcd_mcu.width = 320;
    // g_lcd_mcu.height = 480;
}